name: Cypress Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6.6.0
        with:
          browser: chrome
          working-directory: ./astro
          start: npm run dev
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}

      - uses: actions/upload-artifact@v3
        with:
          name: screenshots-headed-chrome
          path: astro/cypress/screenshots
